spring.application.name=Nhom2_OrderService
server.port=8083
spring.datasource.url=jdbc:mariadb://localhost:3306/order_db?createDatabaseIfNotExist=true
spring.datasource.driver-className=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=25082004
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/auth/.well-known/jwks.json
spring.jpa.show-sql=true
app.services.food-service.url=http://localhost:8082

# ==========================================
# C?U HÌNH RESILIENCE4J - FOOD SERVICE
# ==========================================

# 1. Circuit Breaker
resilience4j.circuitbreaker.instances.FoodService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.FoodService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.FoodService.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.instances.FoodService.minimumNumberOfCalls=20
#10 l?n g?i mà l?i quá 50% thì ng?n k?t n?i 50s ?? foodservice ngh? ng?i
resilience4j.circuitbreaker.instances.FoodService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.FoodService.waitDurationInOpenState=50s
resilience4j.circuitbreaker.instances.FoodService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.FoodService.eventConsumerBufferSize=10

# 2. Retry
#Th? t?i ?a bao nhiêu l?n, m?i l?n cách nhau 5s
resilience4j.retry.instances.FoodService.maxAttempts=3
resilience4j.retry.instances.FoodService.waitDuration=5s
resilience4j.retry.instances.FoodService.enableExponentialBackoff=true
resilience4j.retry.instances.FoodService.exponentialBackoffMultiplier=2
# Quan tr?ng: Ch? th? l?i khi g?p l?i server (5xx) ho?c l?i k?t n?i (I/O)
#resilience4j.retry.instances.FoodService.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
#resilience4j.retry.instances.FoodService.retryExceptions[1]=java.io.IOException

# 3. Rate Limiter
#6 request trong 10 giây
resilience4j.ratelimiter.instances.FoodService.limitForPeriod=6
resilience4j.ratelimiter.instances.FoodService.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.FoodService.timeoutDuration=0
resilience4j.ratelimiter.instances.FoodService.registerHealthIndicator=true
resilience4j.ratelimiter.instances.FoodService.eventConsumerBufferSize=100